### ISSUE TITLE
Project Load Error

### ISSUE THREAD

**Issue by kevinJread** [oslabs-beta/Sylph#87]
1. Installed the application on Mac Book Pro (M1).  
2. Can create a new project 
3. The application displays the spinner but does not progress

The console doesn't display any errors.

Same issue when I run 'open -a Sylph .'

Any ideas?

**Comment by kevinJread** [comment]
I found the fix ....

My project path had spaces in the name.

Sylph worked with the following conditions:

1. No spaces in the path to the Project folder
2. No spaces in the name of the project

**Comment by iva2k** [comment]
@kevinJread - you found a source of the problem and a workaround. It's great!

But the issue of not allowing spaces in path name remains. Why close this issue? It is not truly resolved yet.
